### ISSUE TITLE
Categorising tom_image_grid

### ISSUE THREAD

**Issue by drmonkeyninja** [drmonkeyninja/awesome-textpattern#14]
I've added @Sacripant's tom_image_grid plugin to the list. Not sure where best to categorise it. I've put it under _Images_ but it could easily go under _Admin_. Any preference from others?

**Comment by Sacripant** [comment]
Thanks to add my plugin to your list.
tom_image_grid does'nt bring new feature for images. It just propose a alternative UI for image tab.
So for me under _admin_ is more appropriate.

**Comment by drmonkeyninja** [comment]
Thanks. I've moved it.

Feel free to contribute to awesome-textpattern if you want. It's intended to be a community driven resource. :smiley:
